DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS timestamps;

CREATE TABLE notes (
	basename TEXT PRIMARY KEY, 
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	content TEXT NOT NULL,
	title TEXT NOT NULL
);

CREATE TABLE timestamps (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	ts TIMESTAMP NOT NULL 
);
