DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS timestamps;

CREATE TABLE notes (
	id INTEGER PRIMARY KEY AUTOINCREMENT
	basename TEXT NOT NULL, 
	-- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	created TEXT,
	content TEXT NOT NULL,
	title TEXT NOT NULL
);

CREATE TABLE dates (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	date TIMESTAMP NOT NULL 
);

CREATE TABLE notes_dates (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	note_id INTEGER NOT NULL
	date_id INTEGER NOT NULL
	FOREIGN KEY note_id REFERENCES notes (id)
	FOREIGN KEY date_id REFERENCES dates (id)
)
