DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS dates;
DROP TABLE IF EXISTS notes_dates;
DROP TABLE IF EXISTS notes_links;

CREATE TABLE notes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL, 
	created TIMESTAMP,
	content TEXT NOT NULL,
	title TEXT NOT NULL
);

CREATE TABLE dates (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	date TIMESTAMP NOT NULL 
);

CREATE TABLE notes_dates (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	note_id INTEGER NOT NULL,
	date_id INTEGER NOT NULL,
	FOREIGN KEY (note_id) REFERENCES notes (id),
	FOREIGN KEY (date_id) REFERENCES dates (id)
);

CREATE TABLE notes_links (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	from_note_id INTEGER NOT NULL,
	to_note_id INTEGER NOT NULL,
	FOREIGN KEY (from_note_id) REFERENCES notes (id),
	FOREIGN KEY (to_note_id) REFERENCES notes (id)
);
